name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H 207.154.192.20 >> ~/.ssh/known_hosts

      - name: Debug SSH Key
        run: |
          ssh-add -l
          ssh -T root@207.154.192.20

      - name: Check SSH Connection
        run: ssh -o StrictHostKeyChecking=no root@207.154.192.20 "echo SSH connection successful"

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@207.154.192.20 << 'EOF'
            git pull origin main
            cd RestBank
            docker-compose down
            docker-compose build --no-cache  # Rebuild without cache
            docker-compose up -d             # Start containers in detached mode
          EOF
